In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

df=pd.read_csv("50_Startups.csv")
df

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42  California  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68    New York  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95  California  146121.95
11  100671.96        91790.61        249744.55     Florida  144259.40
12   93863.75       127320.38        249839.44  California  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57    New York  124266.90
19   86419.70       153514.11             0.00     Florida  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26  California  110352.25
23   67532.53       105751.03        304768.73  California  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07    New York  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24    New York   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81    New York   96778.92
34   46426.07       157693.92        210797.67     Florida   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82    New York   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67     Florida   78239.91
41   27892.92        84710.77        164470.71  California   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [ ]:
x=df.iloc[:,:-1].values  #parameters in x   ,result in y
y=df.iloc[:,4].values

In [ ]:
print(x,y)   #parameters are independent so taking as x and y

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'California']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'New York']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'California']
 [100671.96 91790.61 249744.55 'Florida']
 [93863.75 127320.38 249839.44 'California']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'New York']
 [86419.7 153514.11 0.0 'Florida']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'California

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
Label=LabelEncoder()
x[:,3]=Label.fit_transform(x[:,3])

In [ ]:
print(x)

[[0.0 0.0 1.0 48 136897.8 471784.1]
 [1.0 0.0 0.0 47 151377.59 443898.53]
 [0.0 1.0 0.0 46 101145.55 407934.54]
 [0.0 0.0 1.0 45 118671.85 383199.62]
 [1.0 0.0 0.0 44 91391.77 366168.42]
 [0.0 0.0 1.0 42 99814.71 362861.36]
 [1.0 0.0 0.0 43 147198.87 127716.82]
 [0.0 0.0 1.0 41 145530.06 323876.68]
 [0.0 0.0 1.0 39 148718.95 311613.29]
 [1.0 0.0 0.0 40 108679.17 304981.62]
 [1.0 0.0 0.0 36 110594.11 229160.95]
 [0.0 1.0 0.0 35 91790.61 249744.55]
 [1.0 0.0 0.0 33 127320.38 249839.44]
 [1.0 0.0 0.0 32 135495.07 252664.93]
 [0.0 1.0 0.0 38 156547.42 256512.92]
 [0.0 0.0 1.0 37 122616.84 261776.23]
 [1.0 0.0 0.0 28 121597.55 264346.06]
 [0.0 0.0 1.0 34 145077.58 282574.31]
 [0.0 0.0 1.0 31 114175.79 294919.57]
 [0.0 1.0 0.0 30 153514.11 0.0]
 [1.0 0.0 0.0 26 113867.3 298664.47]
 [0.0 0.0 1.0 29 153773.43 299737.29]
 [1.0 0.0 0.0 24 122782.75 303319.26]
 [1.0 0.0 0.0 22 105751.03 304768.73]
 [0.0 0.0 1.0 27 99281.34 140574.81]
 [1.0 0.0 0.0 19 139553.16 137962.62]
 [0.0 0.0 1.0 25 144135.9

In [ ]:
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([('encoder',OneHotEncoder(),[3])],remainder='passthrough')          #onehotencoder assigns values(0,1,2)
x=np.array(ct.fit_transform(x))
print(x)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [1.0 0.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 0.0 1.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [1.0 0.0 0.0 101913.08 110594.11 229160.95]
 [0.0 1.0 0.0 100671.96 91790.61 249744.55]
 [1.0 0.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 0.0 1.0 91749.16 114175.79 294919.57]
 [0.0 1.0 0.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [1.0 0.0 0.0 73994.56 122782.75 3

In [ ]:
print(pd.DataFrame(x).head())

     0    1    2          3          4          5
0  0.0  0.0  1.0   165349.2   136897.8   471784.1
1  1.0  0.0  0.0   162597.7  151377.59  443898.53
2  0.0  1.0  0.0  153441.51  101145.55  407934.54
3  0.0  0.0  1.0  144372.41  118671.85  383199.62
4  1.0  0.0  0.0  142107.34   91391.77  366168.42


In [ ]:
from sklearn.model_selection import train_test_split
train_test_split(x,y)

[array([[0.0, 0.0, 1.0, 61136.38, 152701.92, 88218.23],
        [0.0, 1.0, 0.0, 100671.96, 91790.61, 249744.55],
        [1.0, 0.0, 0.0, 73994.56, 122782.75, 303319.26],
        [1.0, 0.0, 0.0, 101913.08, 110594.11, 229160.95],
        [0.0, 0.0, 1.0, 542.05, 51743.15, 0.0],
        [0.0, 0.0, 1.0, 77044.01, 99281.34, 140574.81],
        [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
        [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
        [0.0, 0.0, 1.0, 55493.95, 103057.49, 214634.81],
        [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
        [0.0, 1.0, 0.0, 46426.07, 157693.92, 210797.67],
        [0.0, 0.0, 1.0, 72107.6, 127864.55, 353183.81],
        [1.0, 0.0, 0.0, 93863.75, 127320.38, 249839.44],
        [0.0, 1.0, 0.0, 1315.46, 115816.21, 297114.46],
        [0.0, 0.0, 1.0, 75328.87, 144135.98, 134050.07],
        [0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
        [0.0, 0.0, 1.0, 1000.23, 124153.04, 1903.93],
        [1.0, 0.0, 0.0, 23640.93, 96189.63, 14

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=14)

In [ ]:
#LinearRegression
print(x.shape)
print(y.shape)
print(x_test.shape)
print(y_test.shape)
print(x_train.shape)
print(y_train.shape)

(50, 6)
(50,)
(10, 6)
(10,)
(40, 6)
(40,)


In [66]:
from sklearn.linear_model import LinearRegression
l=LinearRegression()
l=l.fit(x_train,y_train)
l

LinearRegression()

In [ ]:
y_pred=l.predict(x_test)
y_pred

array([ 47535.66856695, 129854.54622288, 147560.08604486,  92593.62513608,
        80987.91761761,  76535.09922599, 119114.37378388, 176346.03428282,
       170603.01099834, 155286.81639237])

In [ ]:
y_test

array([ 42559.73, 111313.02, 132602.65,  99937.59,  89949.14,  78239.91,
       122776.86, 191792.06, 191050.39, 156122.51])

In [ ]:
result=pd.concat([pd.DataFrame(y_pred,columns=['Prediction']),
                 pd.DataFrame(y_test,columns=['Test'])],axis=1)
result['Difference']=result['Prediction']-result['Test']
result

Prediction       Test    Difference
0   47535.668567   42559.73   4975.938567
1  129854.546223  111313.02  18541.526223
2  147560.086045  132602.65  14957.436045
3   92593.625136   99937.59  -7343.964864
4   80987.917618   89949.14  -8961.222382
5   76535.099226   78239.91  -1704.810774
6  119114.373784  122776.86  -3662.486216
7  176346.034283  191792.06 -15446.025717
8  170603.010998  191050.39 -20447.379002
9  155286.816392  156122.51   -835.693608

In [ ]:
r2_score(y_test,y_pred)

0.9325814961533381

In [ ]:
y_final_pred=l.predict(x)
y_final_pred

array([181013.44637602, 176346.03428282, 170603.01099834, 170146.0192256 ,
       164710.73247584, 161716.93053985, 155286.81639237, 159190.89799265,
       154055.33314702, 153423.03390315, 141182.28269066, 138345.99784237,
       135216.31452616, 133153.40162477, 147560.08604486, 146755.10666913,
       123622.75602923, 140952.52325916, 133365.42148607, 119114.37378388,
       119860.5324182 , 129854.54622288, 115492.63218077, 110289.58151227,
       117832.6581464 ,  98050.66289556, 114059.45877767, 116710.89420052,
       102651.81283428, 101381.00405456,  92593.62513608,  91125.54361837,
        92066.41467632,  91906.09705659,  88554.074201  ,  86295.66448864,
        77737.5775006 ,  80987.91761761,  65906.11422273,  78683.1646758 ,
        76535.09922599,  71178.15426882,  68512.56699161,  59830.92958112,
        63441.08752391,  53748.42863847,  64193.44512239,  47535.66856695,
        49279.81101879,  48649.59160695])

In [ ]:
#final prediction
y_fpred=pd.DataFrame(y_final_pred,columns=['Prediction'])
result=pd.concat([df,y_fpred],axis=1)
result['Difference']=result['Profit']-result['Prediction']
result

R&D Spend  Administration  Marketing Spend       State     Profit  \
0   165349.20       136897.80        471784.10    New York  192261.83   
1   162597.70       151377.59        443898.53  California  191792.06   
2   153441.51       101145.55        407934.54     Florida  191050.39   
3   144372.41       118671.85        383199.62    New York  182901.99   
4   142107.34        91391.77        366168.42  California  166187.94   
5   131876.90        99814.71        362861.36    New York  156991.12   
6   134615.46       147198.87        127716.82  California  156122.51   
7   130298.13       145530.06        323876.68    New York  155752.60   
8   120542.52       148718.95        311613.29    New York  152211.77   
9   123334.88       108679.17        304981.62  California  149759.96   
10  101913.08       110594.11        229160.95  California  146121.95   
11  100671.96        91790.61        249744.55     Florida  144259.40   
12   93863.75       127320.38        249839.44  California  141585.52   
13   91992.39       135495.07        252664.93  California  134307.35   
14  119943.24       156547.42        256512.92     Florida  132602.65   
15  114523.61       122616.84        261776.23    New York  129917.04   
16   78013.11       121597.55        264346.06  California  126992.93   
17   94657.16       145077.58        282574.31    New York  125370.37   
18   91749.16       114175.79        294919.57    New York  124266.90   
19   86419.70       153514.11             0.00     Florida  122776.86   
20   76253.86       113867.30        298664.47  California  118474.03   
21   78389.47       153773.43        299737.29    New York  111313.02   
22   73994.56       122782.75        303319.26  California  110352.25   
23   67532.53       105751.03        304768.73  California  108733.99   
24   77044.01        99281.34        140574.81    New York  108552.04   
25   64664.71       139553.16        137962.62  California  107404.34   
26   75328.87       144135.98        134050.07    New York  105733.54   
27   72107.60       127864.55        353183.81    New York  105008.31   
28   66051.52       182645.56        118148.20     Florida  103282.38   
29   65605.48       153032.06        107138.38    New York  101004.64   
30   61994.48       115641.28         91131.24    New York   99937.59   
31   61136.38       152701.92         88218.23    New York   97483.56   
32   63408.86       129219.61         46085.25  California   97427.84   
33   55493.95       103057.49        214634.81    New York   96778.92   
34   46426.07       157693.92        210797.67     Florida   96712.80   
35   46014.02        85047.44        205517.64    New York   96479.51   
36   28663.76       127056.21        201126.82    New York   90708.19   
37   44069.95        51283.14        197029.42  California   89949.14   
38   20229.59        65947.93        185265.10    New York   81229.06   
39   38558.51        82982.09        174999.30  California   81005.76   
40   28754.33       118546.05        172795.67     Florida   78239.91   
41   27892.92        84710.77        164470.71  California   77798.83   
42   23640.93        96189.63        148001.11  California   71498.49   
43   15505.73       127382.30         35534.17    New York   69758.98   
44   22177.74       154806.14         28334.72  California   65200.33   
45    1000.23       124153.04          1903.93    New York   64926.08   
46    1315.46       115816.21        297114.46     Florida   49490.75   
47       0.00       135426.92             0.00  California   42559.73   
48     542.05        51743.15             0.00    New York   35673.41   
49       0.00       116983.80         45173.06  California   14681.40   

       Prediction    Difference  
0   181013.446376  11248.383624  
1   176346.034283  15446.025717  
2   170603.010998  20447.379002  
3   170146.019226  12755.970774  
4   164710.732476   1477.207524  
5   161716.930540  -4725.810540  
6   155286.816392    835.693608  
7   1591

In [ ]:
r2_score(df['Profit'],y_final_pred)

0.9323956340488667

In [ ]:
a=r2_score(y,y_fpred)
a

0.9323956340488667